### ISSUE TITLE
What is the return Object?

### ISSUE THREAD

**Issue by bokuweb** [argos-ci/image-difference#8]
What is the return Object?

- expected (from README)

```
#### Returns

Promise: Return the difference object with a total and percentage key.
```

- actual (?)

Return `{ width: number, height: number, value: number }` in below code.
`result.percentage` is `undefined`.

https://github.com/bokuweb/reg-cli/blob/0e07428ad88c48dc26c6840cff2dabc2455b1e82/src/index.js#L57-L66

thanks.

**Comment by oliviertassinari** [comment]
I need to update the code. Depending on the metric used, we either returns value or value 1, value2, etc. Those value are in the order of the image magick output. For the `AE` metric, value is the number of different pixels after the fuzz behind applied.

Also, after using the lib two weeks in production, I have noticed that the fuzz implementation of image magick do not perform very well. I might invest into better handling imperceptible changes.

**Comment by bokuweb** [comment]
Thanks for your quick response. Noted with thanks.
I decided to calculate the percentage by reg-cli for now.

**Comment by oliviertassinari** [comment]
> I decided to calculate the percentage by reg-cli for now.

Do it too here https://github.com/argos-ci/argos/blob/master/src/modules/imageDifference/imageDifference.js#L24
